import type { INodeProperties } from 'n8n-workflow';

const createDisplayOptions = {
	show: {
		resource: ['task'],
		operation: ['create'],
	},
};

export const createOperationProperties: INodeProperties[] = [
	{
		displayName: 'Model',
		name: 'model',
		type: 'string',
		default: '',
		required: true,
		description: 'Seedance 模型 ID，例如 doubao-seedance-1-5-pro-251215',
		displayOptions: createDisplayOptions,
	},
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		typeOptions: {
			rows: 4,
		},
		default: '',
		required: true,
		description: '文生视频提示词；节点会自动构造 content[type=text]，不暴露原始 content 数组',
		displayOptions: createDisplayOptions,
	},
	{
		displayName: 'Resolution',
		name: 'resolution',
		type: 'options',
		default: '720p',
		options: [
			{ name: '480p', value: '480p' },
			{ name: '720p', value: '720p' },
			{ name: '1080p', value: '1080p' },
		],
		description: '生成视频分辨率。不同模型支持范围不同',
		displayOptions: createDisplayOptions,
	},
	{
		displayName: 'Ratio',
		name: 'ratio',
		type: 'options',
		default: '16:9',
		options: [
			{ name: '1:1', value: '1:1' },
			{ name: '16:9', value: '16:9' },
			{ name: '21:9', value: '21:9' },
			{ name: '3:4', value: '3:4' },
			{ name: '4:3', value: '4:3' },
			{ name: '9:16', value: '9:16' },
			{ name: 'Adaptive', value: 'adaptive' },
		],
		description: '生成视频宽高比',
		displayOptions: createDisplayOptions,
	},
	{
		displayName: 'Duration',
		name: 'duration',
		type: 'number',
		default: 5,
		description: '视频时长（秒）。与 Frames 二选一；若同时设置会报错',
		displayOptions: createDisplayOptions,
	},
	{
		displayName: 'Frames',
		name: 'frames',
		type: 'number',
		default: '',
		description: '视频帧数。与 Duration 二选一；若同时设置会报错',
		displayOptions: createDisplayOptions,
	},
	{
		displayName: 'Seed',
		name: 'seed',
		type: 'number',
		default: -1,
		description: '控制生成随机性的种子值',
		displayOptions: createDisplayOptions,
	},
	{
		displayName: 'Watermark',
		name: 'watermark',
		type: 'boolean',
		default: false,
		description: 'Whether to include a watermark in the generated video',
		displayOptions: createDisplayOptions,
	},
	{
		displayName: 'Service Tier',
		name: 'serviceTier',
		type: 'options',
		default: 'default',
		options: [
			{ name: 'Default', value: 'default' },
			{ name: 'Flex', value: 'flex' },
		],
		description: '服务等级。不同模型对离线推理支持不同',
		displayOptions: createDisplayOptions,
	},
	{
		displayName: 'Execution Expires After',
		name: 'executionExpiresAfter',
		type: 'number',
		default: 172800,
		description: '任务过期阈值（秒），官方范围通常为 3600 到 259200',
		displayOptions: createDisplayOptions,
	},
	{
		displayName: 'Return Last Frame',
		name: 'returnLastFrame',
		type: 'boolean',
		default: false,
		description: 'Whether to return the generated video last-frame URL when the API supports it',
		displayOptions: createDisplayOptions,
	},
	{
		displayName: 'Generate Audio',
		name: 'generateAudio',
		type: 'boolean',
		default: true,
		description: 'Whether to generate synchronized audio when the selected model supports it',
		displayOptions: createDisplayOptions,
	},
];
